version: '3'

services:
  wp:
    image: wordpress:latest
    ports:
      - 8080:80
    volumes:
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: usermane
       WORDPRESS_DB_PASSWORD: password
       WORDPRESS_DB_NAME: dbname

  wpcli:
    image: wordpress:cli
    volumes:
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - wp